version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
        
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
         ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
         ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
         chmod 600 ~/.ssh/id_rsa
         cd ~/.ssh
         cat id_rsa.pub
         git config --global user.name "nobiraja"
         git config --global user.email "as3776958@gmail.com"
         sleep 60
        
         git clone https://www.opencode.net/romdumprx/oneplus/CPH2661.git -b qssi_64-user-14-UKQ1.231108.001-1721112167802-release-keys-9985 ~/holi 
         git clone https://github.com/OnePlus-Nord4-devs/android_device_oneplus_avalon.git device/oneplus/avalon
         git clone https://github.com/OnePlus-Nord4-devs/android_device_oneplus_sm7675-commo.git device/oneplus/sm7675-common
         git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
         git clone https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools
         ls
         cd device/oneplus/avalon
         chmod u+x setup-makefiles.sh
         chmod u+x extract-files.sh
         ./setup-makefiles.sh
         ./extract-files.sh ~/holi
         cd ..
         cd .. 
         cd ..
         cd vendor/oneplus/avalon
         ls
         git init 
         git add .
         git commit -m "first commit"
         git branch -M main 
         git remote add origin git@github.com:OnePlus-Nord4-devs/vendor_avalon.git
         git push -u origin main
         cd ..
         cd ..
         cd ..
         cd vendor/oneplus/sm7675-common
         git init 
         git add .
         git commit -m "first commit"
         git branch -M main 
         git remote add origin git@github.com:OnePlus-Nord4-devs/vendor_common.git
         git push -u origin main
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
