version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
        
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
         ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
         ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
         chmod 600 ~/.ssh/id_rsa
         cd ~/.ssh
         cat id_rsa.pub
         git config --global user.name "cyberDay777"
         git config --global user.email "asacademybhind@gmail.com"
         sleep 60
        
         git clone https://dumps.tadiphone.dev/dumps/xiaomi/chenfeng.git ~/holi 
         git clone https://github.com/cyberDay777/device_xiaomi_chenfeng.git device/xiaomi/chenfeng
         git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
         git clone https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools
         ls
         cd device/xiaomi/chenfeng
         chmod u+x setup-makefiles.sh
         chmod u+x extract-files.sh
         ./setup-makefiles.sh
         ./extract-files.sh ~/holi
         cd ..
         cd .. 
         cd ..
         cd vendor/xiaomi/chenfeng
         ls
         git init 
         git add .
         git commit -m "first commit"
         git branch -M main 
         git remote add origin git@github.com:cyberDay777/vendor_xiaomi_chenfeng.git
         git push -u origin main
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
