name: My Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  my-job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          sleep 60

      - name: Clone repositories
        run: |
          git clone https://www.opencode.net/romdumprx/oneplus/CPH2661.git ~/holi 
          git clone https://github.com/OnePlus-Nord4-devs/android_device_oneplus_avalon.git device/oneplus/avalon
          git clone https://github.com/OnePlus-Nord4-devs/android_device_oneplus_sm7675-commo.git device/oneplus/sm7675-common
          git clone https://github.com/LineageOS/android_tools_extract-utils.git tools/extract-utils
          git clone https://github.com/LineageOS/android_prebuilts_extract-tools.git prebuilts/extract-tools

      - name: Set up and run scripts
        run: |
          chmod u+x device/oneplus/avalon/setup-makefiles.sh
          chmod u+x device/oneplus/avalon/extract-files.sh
          cd device/oneplus/avalon
          ./setup-makefiles.sh
          ./extract-files.sh ~/holi

      - name: Initialize and push vendor/avalon
        run: |
          cd vendor/oneplus/avalon
          git init 
          git add .
          git commit -m "first commit"
          git branch -M main 
          git remote add origin git@github.com:OnePlus-Nord4-devs/vendor_avalon.git
          git push -u origin main

      - name: Initialize and push vendor/sm7675-common
        run: |
          cd vendor/oneplus/sm7675-common
          git init 
          git add .
          git commit -m "first commit"
          git branch -M main 
          git remote add origin git@github.com:OnePlus-Nord4-devs/vendor_common.git
          git push -u origin main
          
